#!/bin/bash
PIDS=`ps ax | grep "dotnet Discord-Chan.dll" | grep -o '^[ ]*[0-9]*' | grep -v "ps ax"`
PidArray=($PIDS)
lastPid=${PidArray[0]}
if [ -z "$PIDS" ]; then
  echo "Sally can be updated." 1>&2
  exit 1
else
	kill -SIGTERM $lastPid

#echo "Sally cant update, because she is currently running with PID: "$lastPid
#    read -p "Do you want to stop this process (y/n)?" choice
#      case "$choice" in 
#        y|Y ) 
#		kill -SIGTERM $lastPid
#		echo "The bot was shutted down."
#		;;
#        n|N ) echo "Cancled";;
#        * ) echo "invalid";;
#      esac
      
fi
